### ISSUE TITLE
HTTP 404 Error

### ISSUE THREAD

**Issue by mfansler** [pachterlab/ffq#26]
Seeing an HTTP 404 error on an SRR ([SRR19450559](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR19450559)) that is available on SRA. Seems like the issue is that it relies on EBI for the metadata and perhaps it hasn't yet been synced.

```bash
% ffq --verbose SRR19450559       
[2022-06-17 18:52:15,552]   DEBUG Printing verbose output
[2022-06-17 18:52:15,553]   DEBUG Namespace(IDs=['SRR19450559'], aws=False, ftp=False, gcp=False, l=None, ncbi=False, o=None, split=False, t=None, verbose=True)
[2022-06-17 18:52:15,553]    INFO Parsing run SRR19450559
[2022-06-17 18:52:16,069]   ERROR 'HTTPError' object has no attribute 'getcode'
Traceback (most recent call last):
  File "/Users/mfansler/miniconda3/lib/python3.8/site-packages/ffq/utils.py", line 40, in cached_get
    response.raise_for_status()
  File "/Users/mfansler/miniconda3/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error:  for url: https://www.ebi.ac.uk/ena/browser/api/xml/SRR19450559/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mfansler/miniconda3/lib/python3.8/site-packages/ffq/main.py", line 212, in main
    results.append(FFQ[v["prefix"]](v["accession"], args.l))
  File "/Users/mfansler/miniconda3/lib/python3.8/site-packages/ffq/ffq.py", line 355, in ffq_run
    run = parse_run(get_xml(accession))
  File "/Users/mfansler/miniconda3/lib/python3.8/site-packages/ffq/utils.py", line 69, in get_xml
    return BeautifulSoup(cached_get(f'{ENA_URL}/{accession}/'), 'xml')
  File "/Users/mfansler/miniconda3/lib/python3.8/site-packages/ffq/utils.py", line 42, in cached_get
    if exception.getcode() == 429:
AttributeError: 'HTTPError' object has no attribute 'getcode'
{}
```

## System Info

macOS 10.6.7
Python 3.8.12
ffq v0.2.1

**Comment by sbooeshaghi** [comment]
I am able to fetch metadata for this accession with ffq installed from the `devel` branch. Its possible it was a syncing issue between ENA/SRA as it may take a few days for data and metadata to get transferred: 

https://twitter.com/ColmanOC/status/1539881785286443008?s=20&t=km-nTboVGLHQlqfQc_NvjA

```bash
pip install git+https://github.com/pachterlab/ffq.git@devel
ffq SRR19450559
```

**Comment by mfansler** [comment]
Confirmed.
