### ISSUE TITLE
HTTPError' object has no attribute 'getcode' and HTTP 401

### ISSUE THREAD

**Issue by FrankMaiwald** [pachterlab/ffq#28]
Im am running ffq 0.2.1 on Centos 7 (ID_LIKE="rhel fedora") using python 3.7.5
I am in a company network behind a proxy with authorization. The proxy IP, port, user and password are set for http, https, ft, sftp as environment variables. Also, this info is in my .wgetrc, .curlrc, .netrc. 
I use bash as a shell.

A call for an existing SRA experiment fails:

ffq --verbose SRX5256050
[2022-06-30 08:19:03,561]   DEBUG Printing verbose output
[2022-06-30 08:19:03,561]   DEBUG Namespace(IDs=['SRX5256050'], aws=False, ftp=False, gcp=False, l=None, ncbi=False, o=None, split=False, t=None, verbose=True)
[2022-06-30 08:19:03,561]    INFO Parsing Experiment SRX5256050
[2022-06-30 08:19:04,016] WARNING There is 1 run for SRX5256050
[2022-06-30 08:19:04,016]    INFO Parsing run SRR8449072
[2022-06-30 08:19:04,418]   ERROR 'HTTPError' object has no attribute 'getcode'
Traceback (most recent call last):
  File "/usr/prg/python-3.7.5/lib/python3.7/site-packages/ffq/utils.py", line 40, in cached_get
    response.raise_for_status()
  File "/usr/prg/python-3.7.5/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.ebi.ac.uk/ena/portal/api/filereport?accession=SRR8449072&result=read_run&fields=run_accession,fastq_ftp,fastq_md5,fastq_bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/prg/python-3.7.5/lib/python3.7/site-packages/ffq/main.py", line 212, in main
    results.append(FFQ[v["prefix"]](v["accession"], args.l))
  File "/usr/prg/python-3.7.5/lib/python3.7/site-packages/ffq/ffq.py", line 498, in ffq_experiment
    experiment = parse_experiment_with_run(get_xml(accession), level)
  File "/usr/prg/python-3.7.5/lib/python3.7/site-packages/ffq/ffq.py", line 276, in parse_experiment_with_run
    runs = {run: ffq_run(run) for run in runs}
  File "/usr/prg/python-3.7.5/lib/python3.7/site-packages/ffq/ffq.py", line 276, in <dictcomp>
    runs = {run: ffq_run(run) for run in runs}
  File "/usr/prg/python-3.7.5/lib/python3.7/site-packages/ffq/ffq.py", line 355, in ffq_run
    run = parse_run(get_xml(accession))
  File "/usr/prg/python-3.7.5/lib/python3.7/site-packages/ffq/ffq.py", line 116, in parse_run
    ftp_files = get_files_metadata_from_run(soup)
  File "/usr/prg/python-3.7.5/lib/python3.7/site-packages/ffq/utils.py", line 892, in get_files_metadata_from_run
    table = parse_tsv(cached_get(fastq_url))
  File "/usr/prg/python-3.7.5/lib/python3.7/site-packages/ffq/utils.py", line 42, in cached_get
    if exception.getcode() == 429:
AttributeError: 'HTTPError' object has no attribute 'getcode'
{}

but
curl "https://www.ebi.ac.uk/ena/portal/api/filereport?accession=SRR8449072&result=read_run&fields=run_accession,fastq_ftp,fastq_md5,fastq_bytes"
run_accession   fastq_ftp       fastq_md5       fastq_bytes
SRR8449072      ftp.sra.ebi.ac.uk/vol1/fastq/SRR844/002/SRR8449072/SRR8449072_1.fastq.gz;ftp.sra.ebi.ac.uk/vol1/fastq/SRR844/002/SRR8449072/SRR8449072_2.fastq.gz       4402ac7d7929e14d1606b4c3647e4219;175d79964dd97f110ffaf10487c6e1d5   2391514918;2489429551

works as expected.

**Comment by sbooeshaghi** [comment]
This should be fixed with https://github.com/pachterlab/ffq/commit/1d77aeaaaddfcf13fa9d540e161f8db322c017e6. 

```bash
pip install git+https://github.com/pachterlab/ffq.git@devel
ffq SRX5256050
```
